services:
  - type: web
    name: travel-churn-prediction
    env: python
    region: frankfurt
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/models
      sizeGB: 1
